{
    #     "player": "3",
    #     "team": "red",
    #     "position": "attacker_left",
    #     "translation": "-1 0.5 0.4",
    # },
    # {
    #     "player": "4",
    #     "team": "red",
    #     "position": "attacker_right",
    #     "translation": "-1 -0.5 0.4",
    # },
    # {
    #     "player": "1",
    #     "team": "blue",
    #     "position": "goalie",
    #     "translation": "4 0 0.4",
    # },
    # {
    #     "player": "2",
    #     "team": "blue",
    #     "position": "defender",
    #     "translation": "2.5 0 0.4",
    # },
    # {
    #     "player": "3",
    #     "team": "blue",
    #     "position": "attacker_left",
    #     "translation": "1 -0.5 0.4",
    # },
    # {
    #     "player": "4",
    #     "team": "blue",
    #     "position": "attacker_right",
    #     "translation": "1 0.5 0.4",
    # },